package com.diboc.neuralnetworkgenerator.network;

public enum NetworkType {

    PERCEPTRON, FEED_FORWARD,
    RADIAL_BASIS, RECURRENT,
    LONG_SHORT_TERM_MEMORY, GATED_RECURRENT,
    AUTO_ENCODER, VARIATIONAL_AUTO_ENCODER,
    DENOISING_AUTO_ENCODER, SPARSE_AUTO_ENCODER,
    MARKOV_CHAIN, HOPFIELD,
    BOLTZMANN, RESTRICTED_BOLTZMANN,
    CONVOLUTIONAL, DECONVOLUTIONAL,
    CONVOLUTIONAL_INVERSE_GRAPHICS, GENERATIVE_ADVERSARIAL,
    LIQUID_STATE, EXTREME_LEARNING,
    ECHO_STATE, RESIDUAL,
    KOHONEN, SUPPORT_VECTOR,
    NEURAL_TURING

}